ALTER TABLE pregnancies ALTER COLUMN insemination_date SET DEFAULT CURRENT_DATE;
ALTER TABLE pregnancies ALTER COLUMN expected_birth_date SET DEFAULT CURRENT_DATE + 114;
ALTER TABLE pregnancies ALTER COLUMN status SET DEFAULT 'PLANNED';
