ALTER TABLE pigs ALTER COLUMN sex DROP NOT NULL;

ALTER TABLE pigs ALTER COLUMN weight DROP NOT NULL;

ALTER TABLE pigs ALTER COLUMN date_of_birth SET DEFAULT CURRENT_DATE;

ALTER TABLE pigs ALTER COLUMN status SET DEFAULT 'ACTIVE';